package com.jyp.pojo;

public class OrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.id
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.pid
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.oid
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.uid
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.number
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.id
     *
     * @return the value of t_order_item.id
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.id
     *
     * @param id the value for t_order_item.id
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.pid
     *
     * @return the value of t_order_item.pid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.pid
     *
     * @param pid the value for t_order_item.pid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.oid
     *
     * @return the value of t_order_item.oid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.oid
     *
     * @param oid the value for t_order_item.oid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.uid
     *
     * @return the value of t_order_item.uid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.uid
     *
     * @param uid the value for t_order_item.uid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.number
     *
     * @return the value of t_order_item.number
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.number
     *
     * @param number the value for t_order_item.number
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}