package com.jyp.pojo;

public class ProductImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_image.id
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_image.pid
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_image.type
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_image.id
     *
     * @return the value of t_product_image.id
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_image.id
     *
     * @param id the value for t_product_image.id
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_image.pid
     *
     * @return the value of t_product_image.pid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_image.pid
     *
     * @param pid the value for t_product_image.pid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_image.type
     *
     * @return the value of t_product_image.type
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_image.type
     *
     * @param type the value for t_product_image.type
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}