package com.jyp.pojo;

public class Property {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property.id
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property.cid
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property.name
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property.id
     *
     * @return the value of t_property.id
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property.id
     *
     * @param id the value for t_property.id
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property.cid
     *
     * @return the value of t_property.cid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property.cid
     *
     * @param cid the value for t_property.cid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property.name
     *
     * @return the value of t_property.name
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property.name
     *
     * @param name the value for t_property.name
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    @Override
    public String toString() {
        return "Property{" +
                "id=" + id +
                ", cid=" + cid +
                ", name='" + name + '\'' +
                '}';
    }
}