package com.jyp.pojo;

public class PropertyValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property_value.id
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property_value.pid
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property_value.ptid
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private Integer ptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property_value.value
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property_value.id
     *
     * @return the value of t_property_value.id
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property_value.id
     *
     * @param id the value for t_property_value.id
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property_value.pid
     *
     * @return the value of t_property_value.pid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property_value.pid
     *
     * @param pid the value for t_property_value.pid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property_value.ptid
     *
     * @return the value of t_property_value.ptid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public Integer getPtid() {
        return ptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property_value.ptid
     *
     * @param ptid the value for t_property_value.ptid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setPtid(Integer ptid) {
        this.ptid = ptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property_value.value
     *
     * @return the value of t_property_value.value
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property_value.value
     *
     * @param value the value for t_property_value.value
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}