package com.jyp.pojo;

import java.util.Date;

public class Review {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.id
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.content
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.uid
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.pid
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.create_date
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review.id
     *
     * @return the value of t_review.id
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review.id
     *
     * @param id the value for t_review.id
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review.content
     *
     * @return the value of t_review.content
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review.content
     *
     * @param content the value for t_review.content
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review.uid
     *
     * @return the value of t_review.uid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review.uid
     *
     * @param uid the value for t_review.uid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review.pid
     *
     * @return the value of t_review.pid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review.pid
     *
     * @param pid the value for t_review.pid
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review.create_date
     *
     * @return the value of t_review.create_date
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review.create_date
     *
     * @param createDate the value for t_review.create_date
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}