package com.jyp.mapper;

import com.jyp.pojo.PropertyValue;
import com.jyp.pojo.PropertyValueExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PropertyValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_value
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    long countByExample(PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_value
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    int deleteByExample(PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_value
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_value
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    int insert(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_value
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    int insertSelective(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_value
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    List<PropertyValue> selectByExample(PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_value
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    PropertyValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_value
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    int updateByExampleSelective(@Param("record") PropertyValue record, @Param("example") PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_value
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    int updateByExample(@Param("record") PropertyValue record, @Param("example") PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_value
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    int updateByPrimaryKeySelective(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_value
     *
     * @mbg.generated Fri Nov 04 12:18:43 CST 2022
     */
    int updateByPrimaryKey(PropertyValue record);
}